<?php

/**
 * @file
 * Contains hook implementations for tre_jsonapi_custom module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function tre_jsonapi_custom_node_presave(NodeInterface $node) {
  if ($node->bundle() === 'news_item' && $node->hasField('field_markup')) {
    $markup = \Drupal::service('tre_jsonapi_custom.entity_renderer')->renderEntity($node, 'jsonapi');
    $node->set('field_markup', $markup);
  }
}
