log_values: ''
severity_levels:
  emergency: 0
  alert: 0
  critical: 0
  error: 0
  warning: 0
  notice: 0
  info: 0
  debug: 0
method: exclude
syslog_severity_levels:
  emergency: 0
  alert: 0
  critical: 0
  error: 0
  warning: 0
  notice: 0
  info: 0
  debug: 0
syslog_method: exclude
