<?php

/**
 * @file
 * Contains hook implementations for tre_menu_link_alterations module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\link\LinkItemInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * The BASE_FORM_ID in this case being menu_link_content_form.
 */
function tre_menu_link_alterations_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $menu_link_widgets = Element::children($form['link']['widget']);

  foreach ($menu_link_widgets as $widget_delta) {
    $widget =& $form['link']['widget'][$widget_delta];
    $widget['uri']['#link_type'] = LinkItemInterface::LINK_INTERNAL;
    $descriptions =& $widget['uri']['#description']['#items'];
    foreach ($descriptions as &$description) {
      $default_link_string = 'Start typing the title of a piece of content to select it. You can also enter an internal path such as %add-node or an external URL such as %url. Enter %front to link to the front page. Enter %nolink to display link text only. Enter %button to display keyboard-accessible link text only.';
      if (($description instanceof TranslatableMarkup) && ($description->getUntranslatedString() == $default_link_string)) {
        $description = new TranslatableMarkup("Start typing the title of a piece of content to select it.", [], ['context' => 'TRE customised description for menu item link fields.']);
      }
    }
  }
}
