<?php

/**
 * @file
 * Hook implementations for tre_preprocess_embedded_content_and_map_tabs module.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;
use Drupal\datetime_range\Plugin\Field\FieldType\DateRangeItem;
use Drupal\node\NodeInterface;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\tre_preprocess\Plugin\Preprocess\AutomaticPhaseAccordionParagraph;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function tre_preprocess_embedded_content_and_map_tabs_node_presave(NodeInterface $node) {
  _tre_preprocess_embedded_content_and_map_tabs_update_field_listing_search_content($node);
  _tre_preprocess_embedded_content_and_map_tabs_update_field_computed_visibility($node);
  _tre_preprocess_embedded_content_and_map_tabs_update_field_computed_status($node);
}

/**
 * Updates field_listing_search_content for nodes that have it.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node whose field_listing_search_content needs an update.
 */
function _tre_preprocess_embedded_content_and_map_tabs_update_field_listing_search_content(NodeInterface $node) {
  if (!$node->hasField('field_listing_search_content')) {
    return;
  }

  $text_content = [];

  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
  $build = $view_builder->view($node, 'content_tab_card_view_mode');
  $text_content[] = $renderer->renderPlain($build);

  $text_string = implode("\n", $text_content);
  $text_without_tags = strip_tags($text_string);

  $title = $node->getTitle();

  $node->set('field_listing_search_content', "{$title}\n{$text_without_tags}");
}

/**
 * Updates field_computed_visibility for nodes that have it.
 *
 * @todo make this run on cron daily for each node (insert into update queue
 * each day?) (check ->changed)
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node whose field_computed_visibility needs an update.
 */
function _tre_preprocess_embedded_content_and_map_tabs_update_field_computed_visibility(NodeInterface $node) {
  if (!$node->hasField('field_computed_visibility')) {
    return;
  }

  /** @var \Drupal\Core\Entity\EntityRepositoryInterface $entity_repository */
  $entity_repository = \Drupal::service('entity.repository');

  /** @var \Drupal\node\NodeInterface $translated_node */
  $translated_node = $entity_repository->getTranslationFromContext($node);

  $current_date = new DrupalDateTime('now', DateTimeItemInterface::STORAGE_TIMEZONE);
  $current_date_formatted = $current_date->format('Y-m-d');

  $node_visible = FALSE;

  // If any of the daterange fields match the current date, the computed
  // visibility is 'visible'; otherwise 'invisible'.
  foreach (array_keys(AutomaticPhaseAccordionParagraph::FIXED_PHASE_FIELDS) as $field_name) {
    if (!$translated_node->hasField($field_name) || $translated_node->get($field_name)->isEmpty()) {
      continue;
    }

    $phase_paragraphs = $translated_node->get($field_name)->referencedEntities();
    $phase_paragraph = reset($phase_paragraphs);
    if (!($phase_paragraph instanceof ParagraphInterface)) {
      continue;
    }

    /** @var \Drupal\paragraphs\ParagraphInterface $translated_phase */
    $translated_phase = $entity_repository->getTranslationFromContext($phase_paragraph);

    if ($translated_phase->get('field_materials_visibility')->isEmpty()) {
      continue;
    }

    $interval_value = $translated_phase->get('field_materials_visibility')->first();
    // Note: DateRangeItem does not implement an interface that would guarantee
    // the existence of the start_date and end_date properties so comparing
    // against an implementation is necessary.
    if (!($interval_value instanceof DateRangeItem)) {
      continue;
    }

    $start_date = $interval_value->get('start_date')->getValue();
    if (!$start_date instanceof DrupalDateTime) {
      continue;
    }
    $start_date_formatted = $start_date->format('Y-m-d');

    $end_date = $interval_value->get('end_date')->getValue();
    if (!$end_date instanceof DrupalDateTime) {
      continue;
    }
    $end_date_formatted = $end_date->format('Y-m-d');

    $node_visible = $start_date_formatted <= $current_date_formatted && $current_date_formatted <= $end_date_formatted;

    if ($node_visible) {
      break;
    }
  }

  if ($node_visible) {
    $node->set('field_computed_visibility', 'visible');
  }
  else {
    $node->set('field_computed_visibility', 'not_visible');
  }
}

/**
 * Updates field_computed_status for nodes that have it.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node whose field_computed_status needs an update.
 */
function _tre_preprocess_embedded_content_and_map_tabs_update_field_computed_status(NodeInterface $node) {
  /** @var \Drupal\Core\Entity\EntityRepositoryInterface $entity_repository */
  $entity_repository = \Drupal::service('entity.repository');

  if (!$node->hasField('field_computed_status') || !$node->hasField('field_phase')) {
    return;
  }

  /** @var \Drupal\node\NodeInterface $translated_node */
  $translated_node = $entity_repository->getTranslationFromContext($node);

  // When phasing is not in use, we don't want to compute the field.
  if ($node->hasField('field_phasing_not_in_use') && $translated_node->get('field_phasing_not_in_use')->value) {
    return;
  }

  $phase_value = $translated_node->get('field_phase')->getString();
  if ($phase_value === '') {
    return;
  }

  $matching_phases = array_filter(AutomaticPhaseAccordionParagraph::FIXED_PHASE_FIELDS, function ($phase_data) use ($phase_value) {
    return $phase_data['corresponding_phase'] === $phase_value;
  });

  if (count($matching_phases) === 1) {
    $matching_phase = reset($matching_phases);
    $translated_node->set('field_computed_status', $matching_phase['category']);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Resave all the parent nodes when a map-point node gets updated,
 * to update listing_search_content field in the parent nodes.
 */
function tre_preprocess_embedded_content_and_map_tabs_node_update(NodeInterface $node) {
  if ($node->bundle() !== 'map_point') {
    return;
  }

  $parent_nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'field_addresses' => $node->id(),
  ]);

  // Update the search field of all parent nodes when a map_point node gets
  // updated.
  foreach ($parent_nodes as $parent_node) {
    $parent_node->save();
  }

}

/**
 * Implements hook_cron().
 */
function tre_preprocess_embedded_content_and_map_tabs_cron() {
  // Get last cron run timestamp.
  $last_run_timestamp = \Drupal::state()->get('tre_content_and_map_cron_last_run', 0);

  // If no previous cron run was found, default to past 24 hours
  // so we don't miss data between deployments.
  if ($last_run_timestamp === 0) {
    $last_run_timestamp = \Drupal::time()->getRequestTime() - 24 * 3600;
  }

  // Convert the timestamp to a datetime object for queuring.
  $last_run_datetime = new DrupalDateTime('@' . $last_run_timestamp, new \DateTimeZone('UTC'));

  // Only insert nodes into the automatic update queue that have not been
  // updated since the last cron run. This is to save resources, since the ones that have been
  // updated already have the correct values in place for the
  // metadata (field_computed_visibility).
  _tre_preprocess_embedded_content_and_map_tabs_insert_nodes_into_queue($last_run_datetime);

  // Save timestamp for the current cron run.
  \Drupal::state()->set('tre_content_and_map_cron_last_run', \Drupal::time()->getRequestTime());
}

/**
 * Inserts nodes into a queue for automated updates of time-dependent metadata.
 *
 * @param \Drupal\Core\Datetime\DrupalDateTime $since
 *   The limit value for 'changed' in nodes; any nodes that have been updated
 *   after than this time limit are included in the queue.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function _tre_preprocess_embedded_content_and_map_tabs_insert_nodes_into_queue(DrupalDateTime $since): void {
  $since_utc = clone $since;
  $since_utc->setTimezone(new \DateTimeZone(DateTimeItemInterface::STORAGE_TIMEZONE));
  $current_datetime = new DrupalDateTime('now', DateTimeItemInterface::STORAGE_TIMEZONE);
  $today = $current_datetime->format('Y-m-d');

  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');

  $content_types = [
    'comprehensive_plan',
    'city_planning_and_constructions',
    'zoning_information',
  ];

  // Query 1) Fetch nodes that were changed after the last cron run timestamp.
  $node_query = $node_storage
    ->getQuery()
    ->accessCheck(FALSE);
  $node_query->condition('type', $content_types, 'IN');
  $node_query->condition('changed', $since_utc->getTimestamp(), '>');
  $nids = $node_query->execute();

  // Query 2) fetch accordion paragraphs that have field_materials_visibility
  // start date today or end date that has passed.
  $paragraph_query = $paragraph_storage
    ->getQuery()
    ->accessCheck(FALSE);
  $query_group = $paragraph_query->orConditionGroup()
    ->condition('field_materials_visibility.value', $today, '=')
    ->condition('field_materials_visibility.end_value', $today, '<');
  $paragraph_query->condition($query_group);
  $paragraph_ids = $paragraph_query->execute();

  $date_nids = [];
  if (!empty($paragraph_ids)) {
    // Go through found accordion paragraphs.
    $paragraphs = $paragraph_storage->loadMultiple($paragraph_ids);
    foreach ($paragraphs as $paragraph) {
      // Get the related parent node.
      $parent = $paragraph->getParentEntity();

      // Check that parent is a node and not null.
      if (!($parent instanceof NodeInterface)) {
        continue;
      }

      // Check if parent node type matches the specified content types.
      if (in_array($parent->getType(), $content_types)) {
        // Add matching parent nodes for processing.
        $date_nids[] = $parent->id();
      }
    }
  }

  // Merge the two sets of nodes ids.
  $grouped_nodes = array_merge($nids, $date_nids);
  // Clear duplicates if node id is found in both sets.
  $nids_to_process = array_unique($grouped_nodes);

  if (count($nids_to_process) === 0) {
    return;
  }

  $queue = \Drupal::queue('tre_list_and_map_update_field_computed_visibility', TRUE);
  foreach ($nids_to_process as $nid) {
    $queue->createItem(['nid' => $nid]);
  }
}
