label: 'Kiinteä jatkolinkki'
description: 'Tähän tulee heron kiinteä linkki (esim. "Jatka kaikkiin ajankohtaisiin"). Koska tämä vie etusivun uutisosioon, kirjoita URL-kenttään haluamasi uutis-paragraafin ankkuri (esim. #paragraph-72990).'
