{
  "root": true,
  "extends": [
    "airbnb-base",
    "plugin:security/recommended",
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "security",
    "prettier",
    "jsx-a11y",
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "es6": true,
    "browser": true
  },
  "globals": {
    "expect": true,
    "it": true,
    "describe": true,
    "Drupal": true,
    "once": true
  },
  "parser": "@babel/eslint-parser",
  "rules": {
    "strict": 0,
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    ],
    "import/no-extraneous-dependencies": 0,
    "react/prefer-stateless-function": 0,
    "jsx-a11y/label-has-for": [
      2,
      {
        "required": {
          "some": [
            "nesting",
            "id"
          ]
        }
      }
    ]
  },
  "overrides": [
    {
      "files": [
        "*.stories.js"
      ],
      "rules": {
        "react/no-danger": 0,
      }
    }
  ]
}