content:
  field_anchor_list_title:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
  field_text:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
