third_party_settings:
  field_group:
    group_categorization:
      label: Categorization
    group_display_archive_link:
      label: 'Link to portfolio listing page'
      format_settings:
        description: 'You can hide the link to the portfolio content listing page here.'
