third_party_settings:
  field_group:
    group_categorization:
      label: Categorization
    group_display_archive_link:
      label: 'Display archive link'
      format_settings:
        description: 'You can add a link to the portfolio content listing page here.'
