third_party_settings:
  field_group:
    group_addresses:
      label: Addresses
    group_opening_hours_1:
      label: 'Opening hours 1'
    group_opening_hours_2:
      label: 'Opening hours 2'
    group_opening_hours_3:
      label: 'Opening hours 3'
content:
  field_additional_phones:
    third_party_settings:
      ds:
        ft:
          settings:
            lb: Phone
  field_addresses:
    third_party_settings:
      ds:
        ft:
          settings:
            lb: Address
  field_email:
    third_party_settings:
      ds:
        ft:
          settings:
            pattern_settings:
              icon_field_group:
                field_label: Email
