content:
  field_address:
    third_party_settings:
      ds:
        ft:
          settings:
            lb: Address
  field_addresses:
    third_party_settings:
      ds:
        ft:
          settings:
            lb: Address
