third_party_settings:
  field_group:
    group_main_image:
      label: 'Main image and caption'
    group_general:
      label: General
    group_categorization:
      label: Categorization
    group_search_keywords:
      label: 'Search keywords'
