third_party_settings:
  field_group:
    group_main_image:
      format_settings:
        description: 'Main image and its caption'
      label: 'Main image and caption'
    group_tabs:
      label: Tabs
    group_general:
      label: General
    group_categorization:
      label: Categorization
    group_search_keywords:
      label: 'Search keywords'
