label: 'Search keywords'
description: 'Is used in search functionality to lift up content. Write 1-3 of the most relevant terms specifically related to your content, not a list of several general terms related to the topic.'
