label: 'Life Situations'
description: 'Is used to direct content to automatic content listings on pages, and to allow the customer to filter by life situation to find content in searches on the site.'
