settings:
  allowed_values:
    -
      label: Survey
    -
      label: Voting
    -
      label: Hearing
    -
      label: Discussion
    -
      label: Workshop
    -
      label: Bee
    -
      label: Celebration
    -
      label: Brainstorming
    -
      label: 'Other participation'
