label: 'Organizational unit'
description: 'Translate the units into English using the <a target="_blank" href="/en/admin/structure/taxonomy/manage/personnel_organization_units/overview">vocabulary management</a>!'
