label: 'First text column'
description: 'The field contents are displayed in the first column of the footer on large devices. Please use the key combination CTRL+SHIFT + V to paste from an external source.'
