label: 'Text without background color'
description: 'Select text from the Text or Image field to display this text. You can add text here if the width of the text with the background color is one-third or half a column. It is not displayed if the text with the background color takes up the entire width of the column.'
