settings:
  allowed_values:
    -
      label: Place
    -
      label: 'Local detailed plan'
    -
      label: 'Comprehensive plan'
    -
      label: 'City planning and construction project'
    -
      label: 'Place of business'
