label: 'Description for the embed contents for screen readers'
description: "For accessibility reasons, a brief description or a descriptive name for the embed should be given for screen readers. For example, <i>The library's location on a map</i>."
