label: 'Page content'
description: 'Add here content for the 404 error page, that will be shown to visitor, if page is not found. Please use the key combination CTRL+SHIFT + V to paste from an external source.'
