label: 'Cost center'
description: 'Translate the cost centers into English using the <a target="_blank" href="/en/admin/structure/taxonomy/manage/personnel_cost_centers/overview">vocabulary management</a>!'
