settings:
  allowed_values:
    0:
      label: Assistant
    1:
      label: 'Accessible parking'
    2:
      label: 'Accessible entrance'
    3:
      label: 'Accessible WC'
    4:
      label: Lift
    5:
      label: 'Induction loop'
    8:
      label: 'Coffee shop'
    9:
      label: Store
    10:
      label: 'Conference room'
    11:
      label: 'Equipment on loan'
    12:
      label: 'Childcare room'
    13:
      label: 'Charging spot'
    14:
      label: 'Ticket sales'
    15:
      label: Ramp
    16:
      label: 'Services helping visually impared'
    17:
      label: 'Guide dogs allowed'
    18:
      label: Braille
    19:
      label: 'Stair lift'
    20:
      label: Stairs
    21:
      label: 'Wheelchair lift'
    22:
      label: Rollator
    23:
      label: 'Electric moped park'
    24:
      label: Locker
    25:
      label: 'Large text'
    26:
      label: Cloakroom
    27:
      label: 'Services in sign language'
    29:
      label: 'Accessible WC, one-sidedly usable left'
    30:
      label: 'Accessible WC, one-sidedly usable right'
    31:
      label: 'Sound guidance'
    32:
      label: 'ISA combination'
