tags:
  og_title: '[current-page:title] [City of Tampere]'
  description: 'The City of Tampere web pages: information on the city services and current issues, access to the electronic services of the City of Tampere.'
  og_description: 'The City of Tampere web pages: information on the city services and current issues, access to the electronic services of the City of Tampere.'
  canonical_url: '[current-page:url]'
  title: '[current-page:title] | [site:name]'
label: Global
