description: 'Displays location related content in two tabs. The first tab shows a list of compact contact cards for the locations, and the second tab displays the same locations on a map.'
label: 'Embedded content and map tabs'
