description: 'Find and manage media.'
display:
  default:
    display_title: Default
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: 'Media name'
        bundle:
          label: Type
        uid:
          label: Author
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      empty:
        area_text_custom:
          content: 'No media available.'
      filters:
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: 'True'
            description: ''
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
        populate:
          expose:
            label: Name
            description: 'Search for image by name or file name or both.'
