display:
  default:
    display_options:
      filters:
        populate:
          expose:
            label: Name
            description: 'Search for image by name or file name or both.'
        filename:
          expose:
            label: 'File name'
        status:
          expose:
            label: 'Publishing status'
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: 'Media type'
          group_info:
            label: 'Media type'
      title: Media
      fields:
        media_bulk_form:
          action_title: Action
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: 'Apply filters'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No media available.'
      sorts:
        created:
          expose:
            label: 'Newest first'
        name:
          expose:
            label: 'Name (A-Z)'
        name_1:
          expose:
            label: 'Name (Z-A)'
    display_title: Default
  page:
    display_options:
      filters:
        populate:
          expose:
            label: Name
            description: 'Search for image by name or file name or both.'
    display_title: Page
  widget:
    display_options:
      filters:
        populate:
          expose:
            label: Name
            description: 'Search for image by name or file name or both.'
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
    display_title: Widget
  widget_table:
    display_options:
      filters:
        populate:
          expose:
            label: Name
            description: 'Search for image by name or file name or both.'
        name:
          expose:
            label: Name
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Updated
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
    display_title: 'Widget (table)'
label: 'Media library'
description: 'Find and manage media.'
