label: 'Chance for participation moderation'
type_settings:
  states:
    archived:
      label: Archived
    draft:
      label: Draft
    draft_state:
      label: Draft
    in_review:
      label: 'In review'
    published:
      label: Published
  transitions:
    archive:
      label: Archive
    create_draft:
      label: 'Create draft'
    julkaise:
      label: Publish
    restore_draft:
      label: 'Restore draft'
    send_for_review:
      label: 'Send for review'
