severity_levels:
  emergency: false
  alert: false
  critical: false
  error: false
  warning: false
  notice: false
  info: false
  debug: false
log_values: {  }
log_values_regex: {  }
method: exclude
syslog_severity_levels:
  emergency: false
  alert: false
  critical: false
  error: false
  warning: false
  notice: false
  info: false
  debug: false
syslog_log_values: {  }
syslog_log_values_regex: {  }
syslog_method: exclude
