<?php

/**
 * @file
 * Contains hook implementations for tre_admin_theme_modifications module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function tre_admin_theme_modifications_preprocess_page(&$variables) {
  return _tre_admin_theme_modifications_preprocess($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tre_admin_theme_modifications_preprocess_html__entity_browser__modal(&$variables) {
  return _tre_admin_theme_modifications_preprocess($variables);
}

/**
 * Helper function for admin theme preprocessing.
 *
 * @param array $variables
 *   The parameter variables for the original preprocess hook.
 *
 * @return array
 *   The preprocessed variables as an array.
 */
function _tre_admin_theme_modifications_preprocess(array &$variables): array {
  $variables['page']['#cache']['contexts'][] = 'theme';

  $config = \Drupal::config('system.theme');
  $theme = \Drupal::theme()->getActiveTheme()->getName();

  if ($theme === $config->get('admin')) {
    $variables['#attached']['library'][] = 'tre_admin_theme_modifications/custom-admin';
  }

  return $variables;
}
