severity_levels:
  emergency: false
  alert: false
  critical: false
  error: false
  warning: false
  notice: false
  info: false
  debug: false
log_values:
  - tre_hr_import|info
  - 'openid_connect|emergency,alert,critical,error,warning,notice,info,debug'
  - 'tre_node_location_coordinate_conversion|alert,error,warning,notice,info,debug'
log_values_regex: {  }
method: include
syslog_severity_levels:
  emergency: false
  alert: false
  critical: false
  error: false
  warning: false
  notice: false
  info: false
  debug: false
syslog_log_values:
  - user|notice
  - permission_watchdog|notice
  - role_watchdog|notice
  - entity_log|info
  - 'content|notice,info'
  - php|error
  - 'tre_ptv_import|warning,error'
  - 'tre_preprocess_migration|info,notice'
syslog_log_values_regex: {  }
syslog_method: include
