<?php

/**
 * @file
 * Module tre_mtm.module.
 */

/**
 * Implements hook_page_attachments().
 */
function tre_mtm_page_attachments(array &$page) {
  $config = \Drupal::config('tre_mtm.settings');
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

  $admin_pages = ($config->get('admin-pages') || !$is_admin);

  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $renderer->addCacheableDependency($page, $config);

  $container_urls_value = array_filter($config->get('container_urls'));
  if (empty($container_urls_value)) {
    return;
  }

  if ($config->get('enable') && $admin_pages) {
    $container_string = '["' . implode('", "', $container_urls_value) . '"]';
    // Instead of insertBefore() on the first script, let's insert after the
    // first script which is the Cookieinformation consent mode script which
    // should remain the first script at all times.
    $script = <<<END
    var mtm = window._mtm = window._mtm || [];
    mtm.push({ 'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start' });
    (
      function () {
        var d = document, s = d.getElementsByTagName('script')[0];
        var scripts = $container_string;
        scripts.forEach(function (src) {
          var g = d.createElement('script');
          g.type = 'text/javascript'; g.async = true; g.src = src;
          s.parentNode.insertBefore(g, s.nextSibling);
        });
      }
    )();
END;

    $page['#attached']['html_head'][] = [
      ['#tag' => 'script', '#value' => $script],
      'tre_mtm',
    ];
  }
}
