<?php

/**
 * @file
 * Contains tre_language_switcher_links.module.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\node\NodeInterface;

/**
 * Implements hook_language_switch_links_alter().
 */
function tre_language_switcher_links_language_switch_links_alter(array &$links, $type, $path) {
  $links = _tre_language_switcher_links_modify_language_titles($links);
  $links = _tre_language_switcher_links_modify_minisite_language_links($links);
}

/**
 * Helper function to modify language switcher titles.
 *
 * @param array $links
 *   The language switcher links.
 *
 * @return array
 *   Modified links.
 */
function _tre_language_switcher_links_modify_language_titles(array $links) {
  $active_theme_name = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  $default_theme_name = \Drupal::config('system.theme')->get('default');
  $current_lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if ($active_theme_name == $default_theme_name) {
    $span_string = '<span aria-hidden="true">@lang_code</span><span class="visually-hidden">@description</span>';

    foreach ($links as $lang_id => $link) {
      if ($current_lang_code === $lang_id) {
        $links[$lang_id]['attributes']['aria-current'] = 'true';
      }

      if ($lang_id == 'fi') {
        $links[$lang_id]['title'] = new FormattableMarkup($span_string, [
          '@lang_code' => 'FI',
          '@description' => 'Valitse sivuston kieli: suomi',
        ]);
      }
      elseif ($lang_id == 'en') {
        $links[$lang_id]['title'] = new FormattableMarkup($span_string, [
          '@lang_code' => 'EN',
          '@description' => 'Select site language: English',
        ]);
      }
    }
  }
  return $links;
}

/**
 * Alters the language switcher link destinations for minisite content.
 *
 * Language switcher links for minisite content should point to the minisite's
 * own front page (as opposed to the main site front page) when no translation
 * is available for a node in a given language. However, the links should not
 * get altered if the minisite does not have a front page or it lacks the
 * appropriate translation.
 *
 * @param array $links
 *   The language switcher links.
 *
 * @return array
 *   Modified links.
 */
function _tre_language_switcher_links_modify_minisite_language_links(array $links) {
  $helper_functions = \Drupal::service('tre_preprocess_utility_functions.helper_functions');
  $current_group = $helper_functions->getCurrentGroup();

  if (!$current_group || !$helper_functions->isMinisite()) {
    return $links;
  }

  foreach ($links as $lang_id => $link) {
    if ($links[$lang_id]['url']->getRouteName() !== '<front>') {
      continue;
    }

    if (!$current_group->hasField('field_front_page') || $current_group->get('field_front_page')->isEmpty()) {
      continue;
    }

    $group_front_page = $current_group->get('field_front_page')->entity;

    if (!($group_front_page instanceof NodeInterface)) {
      continue;
    }

    if (!$group_front_page->hasTranslation($lang_id)) {
      continue;
    }

    $translated_front_page = $group_front_page->getTranslation($lang_id);

    $links[$lang_id]['url'] = $translated_front_page->toUrl();

  }

  return $links;
}
