_core:
  default_config_hash: nIukw9bx_qoTpVohqB0yv-wF86MujULRy_zw2u2_3mk
provider: openai__gpt-4o-mini
token_limit: 8000
auto_apply_suggestions: false
auto_apply_relevance_levels:
  - high
  - medium
