_core:
  default_config_hash: qSffC70ODbv0BehNMS_7K1sO34OogvBsnphKkBeV5W8
langcode: fi
admin_css: true
fx: ''
noscript: false
one_pixel: true
placeholder: ''
unstyled_extensions: ''
responsive_image: false
blazy:
  loadInvisible: true
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: null
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
