_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: fi
ignored_config_entities:
  - 'webform.webform.*'
  - 'siteimprove.settings:api_username'
  - 'siteimprove.settings:api_key'
