_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: fi
mode: simple
ignored_config_entities:
  - 'siteimprove.settings:api_key'
  - 'siteimprove.settings:api_username'
  - 'webform.webform.*'
