_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fi
module:
  backward_compatibility: -1000
  address: 0
  address_display: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  antibot: 0
  auto_entitylabel: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cache_tags: 0
  ckeditor: 0
  color: 0
  color_field: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_pages: 0
  config_split: 0
  config_translation: 0
  content_moderation: 0
  content_moderation_notifications: 0
  cookieinformation: 0
  crop: 0
  datetime: 0
  datetime_range: 0
  decorative_image_widget: 0
  diff: 0
  dropzonejs: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  elb: 0
  embederator: 0
  emulsify_twig: 0
  entity: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entity_reference_unpublished: 0
  entity_type_clone: 0
  entity_usage: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  ex_icons: 0
  external_data_source: 0
  facets: 0
  facets_custom_label: 0
  feeds: 0
  field: 0
  field_delimiter: 0
  field_group: 0
  field_states_ui: 0
  field_ui: 0
  file: 0
  file_delete: 0
  filter: 0
  focal_point: 0
  form_display_field_machine_name: 0
  geofield: 0
  gnode: 0
  group: 0
  group_content_menu: 0
  group_scheduled_transitions: 0
  heading: 0
  help: 0
  image: 0
  image_style_warmer: 0
  imagecache_external: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_boost: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  jsonapi_image_styles: 0
  jsonapi_include: 0
  language: 0
  language_switcher_extended: 0
  layout_discovery: 0
  lazy: 0
  link: 0
  linkit: 0
  locale: 0
  mailsystem: 0
  markdown: 0
  markup: 0
  markup_field: 0
  maxlength: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_entity_dreambroker: 0
  media_entity_file_replace: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_item_extras: 0
  menu_ui: 0
  message: 0
  message_notify: 0
  metatag: 0
  metatag_favicons: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_override: 0
  migrate_plus: 0
  migrate_source_csv: 0
  mimemail: 0
  mysql: 0
  node: 0
  office_hours: 0
  open_readspeaker: 0
  openid_connect: 0
  options: 0
  options_table: 0
  override_node_options: 0
  page_cache: 0
  paragraph_view_mode: 0
  paragraphs_admin: 0
  paragraphs_asymmetric_translation_widgets: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  path_guard: 0
  preprocess: 0
  quick_node_clone: 0
  quicklink: 0
  rabbit_hole: 0
  redirect: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  robotstxt: 0
  role_delegation: 0
  scheduled_transitions: 0
  scn: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_mapping: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  serialization: 0
  simple_responsive_table: 0
  simple_sitemap: 0
  siteimprove: 0
  slick: 0
  slick_ui: 0
  social_media: 0
  social_media_links: 0
  svg_image_field: 0
  syslog: 0
  system: 0
  system_status: 0
  tablefield: 0
  taxonomy: 0
  telephone: 0
  telephone_plus: 0
  term_reference_tree: 0
  text: 0
  timesup: 0
  token: 0
  toolbar: 0
  tre_breadcrumbs_custom: 0
  tre_course_listing: 0
  tre_current_content_archive_search_content: 0
  tre_custom_document_titles: 0
  tre_custom_paths: 0
  tre_display_external_events: 0
  tre_external_publish_permissions: 0
  tre_group_admin_fixes: 0
  tre_group_module_custom: 0
  tre_hr_import: 0
  tre_jsonapi_custom: 0
  tre_language_switcher_links: 0
  tre_lazyload_field_formatters: 0
  tre_link_field_formatter: 0
  tre_menu_link_alterations: 0
  tre_minisite_breadcrumb: 0
  tre_mtm: 0
  tre_news_archive: 0
  tre_news_email_release: 0
  tre_node_location_coordinate_conversion: 0
  tre_node_logger: 0
  tre_openid_connect_windows_aad_tampere: 0
  tre_openid_connect_windows_aad_tampere_edu: 0
  tre_openid_connect_windows_aad_tampere_opetus: 0
  tre_phone_field_formatter: 0
  tre_preprocess: 0
  tre_preprocess_embedded_content_and_map_tabs: 0
  tre_preprocess_utility_functions: 0
  tre_ptv_import: 0
  tre_react_and_share: 0
  tre_related_news_group_check: 0
  tre_search_exclusion: 0
  tre_tablefield_column_drag: 0
  tre_wp_sites_import: 0
  twig_tweak: 0
  ui_patterns: 0
  ui_patterns_ds: 0
  ui_patterns_field_group: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_settings: 0
  ui_patterns_views: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  variationcache: 0
  views_custom_cache_tag: 0
  views_ui: 0
  warmer: 0
  warmer_cdn: 0
  webform: 0
  webform_paragraphs: 0
  webform_translation_permissions: 0
  webform_ui: 0
  workflows: 0
  ds: 1
  limited_field_widgets: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  formdazzle: 10
  views: 10
  paragraphs: 11
  publication_date: 99
  codebase: 1000
theme:
  stark: 0
  stable: 0
  seven: 0
  tampere: 0
profile: codebase
