id: full_name_firstname_first
label: 'Full name (firstname lastname)'
ui_limit: 'person|*'
type: token
type_label: 'Token field'
entities:
  node: node
properties:
  content:
    value: '[node:field_first_names] [node:field_last_name]'
    format: plain_text
