_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
langcode: fi
local_task_enabled_entity_types:
  - media
track_enabled_source_entity_types:
  - block_content
  - config_pages
  - group
  - group_content
  - media
  - node
  - paragraph
track_enabled_target_entity_types:
  - block_content
  - config_pages
  - group
  - group_content
  - media
  - node
  - paragraph
track_enabled_plugins:
  - dynamic_entity_reference
  - media_embed
  - entity_reference
  - entity_embed
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
