_core:
  default_config_hash: J6QBFdEYFecHpT05_8KmHuTn9k9ELLdiLJO-fQS1nDk
langcode: fi
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    fi: ''
    en: en
    '': null
  domains:
    fi: ''
    en: ''
selected_langcode: fi
