_core:
  default_config_hash: MyabvDT1FAaMt3eMLoQ_yg17eopyAABvcOxZ5spt5kk
langcode: fi
skipClass: no-lazy
disable_admin: true
visibility:
  id: request_path
  pages: "/ajankohtaista/artikkelit.xml\r\n/ajankohtaista/ilmoitukset.xml\r\n/ajankohtaista/uutiset.xml\r\n/current/news.xml"
  negate: 0
placeholderSrc: ''
preferNative: false
cssEffect: false
minified: true
libraryPath: /libraries/lazysizes
lazysizes:
  lazyClass: lazyload
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: lazyerror
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins: {  }
