_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: tampere
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  message_notify:
    none:
      sender: mime_mail
      formatter: mime_mail
  webform:
    none:
      sender: webform_php_mail
      formatter: webform_php_mail
