_core:
  default_config_hash: CAJ-9AcdYeNTIjOw77fZlHfAJ4cNRPriq3VgOgOaNLw
entity_type_groups:
  node:
    person:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
separator: ;
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: 200
  metatag_maxlength_abstract: null
  metatag_maxlength_og_description: 200
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_twitter_cards_label2: null
  metatag_maxlength_twitter_cards_label1: null
  metatag_maxlength_twitter_cards_description: null
  metatag_maxlength_twitter_cards_title: null
tag_trim_end: '|.,-:;/+&([{"'''
