enabled: tampere_fi
settings:
  redirect_url: ''
  client_id: will-be-overridden
  client_secret: will-be-overridden
  enable_single_sign_out: 1
  authorization_endpoint_wa: 'https://example.com/oauth2/authorize'
  token_endpoint_wa: 'https://example.com/oauth2/token'
  map_ad_groups_to_roles: 0
  group_mapping:
    method: '0'
    mappings: ''
    strict: 0
  userinfo_graph_api_wa: '1'
  userinfo_endpoint_wa: 'https://example.com/oauth2/UserInfo'
  userinfo_graph_api_use_other_mails: 0
  userinfo_update_email: 0
  hide_email_address_warning: 1
_core:
  default_config_hash: zKCZci5IzwHTf3xysPemd4YQsOPQ4rce90VKNpk7PeI
langcode: fi
