_core:
  default_config_hash: YpBA3MmDuJpZ9SM3DE4kR0lTY89bf2y3g0sS7s3TQ4k
langcode: fi
always_save_userinfo: true
connect_existing_users: true
override_registration_settings: true
user_login_display: above
userinfo_mappings:
  timezone: zoneinfo
  metatag: '0'
  role_change: '0'
  path: '0'
redirect_login: user
redirect_logout: ''
end_session_enabled: true
