_core:
  default_config_hash: blfmQx2l-O0o6lCjybd2SQ2mMo0Qv7USRev0G4O--QE
langcode: fi
mirror_operations:
  'view scheduled transition': update
  'add scheduled transition': update
  'reschedule scheduled transitions': update
automation:
  cron_create_queue_items: true
bundles:
  -
    entity_type: node
    bundle: basic_content_page
  -
    entity_type: node
    bundle: blog_article
  -
    entity_type: node
    bundle: city_planning_and_constructions
  -
    entity_type: node
    bundle: collection_page
  -
    entity_type: node
    bundle: front_page
  -
    entity_type: node
    bundle: involvement_opportunity
  -
    entity_type: node
    bundle: news_item
  -
    entity_type: node
    bundle: notice
  -
    entity_type: node
    bundle: organization
  -
    entity_type: node
    bundle: place
  -
    entity_type: node
    bundle: portfolio
  -
    entity_type: node
    bundle: project
  -
    entity_type: node
    bundle: rich_article
  -
    entity_type: node
    bundle: small_news_item
  -
    entity_type: node
    bundle: zoning_information
message_transition_latest: 'Scheduled transition: transitioning latest revision from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_historical: 'Scheduled transition: copied revision #[scheduled-transitions:from-revision-id] and changed from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_copy_latest_draft: 'Scheduled transition: reverted [scheduled-transitions:latest-state] revision #[scheduled-transitions:latest-revision-id] back to top'
message_override: false
