social_media:
  facebook_share:
    enable: 1
    text: Facebook
    api_url: 'http://www.facebook.com/share.php?u=[current-page:url]&title=[current-page:title]'
    api_event: href
    default_img: 0
    weight: '1'
    attributes: "target|_blank\r\nclass|facebook\r\n"
    drupalSettings: ''
    library: ''
    img: /themes/custom/tampere/images/icon-sets/main-site-icons/facebook.svg
  facebook_msg:
    enable: 0
    api_url: 'FB.ui({method: ''send'',link: ''[current-page:url]''})'
    api_event: onclick
    drupalSettings: 'application_id|Your Application ID'
    library: social_media/facebook
    text: 'Facebook messenger'
    default_img: 1
    weight: '5'
    attributes: "target|_blank\r\nclass|facebook-msg\r\n"
    img: ''
  linkedin:
    enable: 1
    api_url: 'http://www.linkedin.com/shareArticle?mini=true&url=[current-page:url]&title=[current-page:title]&source=[current-page:url]'
    api_event: href
    text: Linkedin
    default_img: 0
    weight: '3'
    attributes: "target|_blank\r\nclass|linkedin\r\n"
    drupalSettings: ''
    library: ''
    img: /themes/custom/tampere/images/icon-sets/main-site-icons/linkedin.svg
  twitter:
    enable: 1
    api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&url=[current-page:url]&hashtags=Hashtag'
    api_event: href
    text: Twitter
    default_img: 0
    weight: '2'
    attributes: "target|_blank\r\nclass|twitter\r\n"
    drupalSettings: ''
    library: ''
    img: /themes/custom/tampere/images/icon-sets/main-site-icons/twitter.svg
  pinterest:
    enable: 0
    api_url: 'https://www.pinterest.com/pin/create/button/?url=[current-page:url]&description=[current-page:title]'
    api_event: href
    text: Pinterest
    default_img: 1
    weight: '5'
    attributes: "target|_blank\r\nclass|pinterest\r\n"
    drupalSettings: ''
    library: ''
    img: ''
  whatsapp:
    enable: 0
    api_url: 'https://wa.me/?text=[current-page:url]'
    api_event: href
    default_img: 1
    attributes: "class|whatsapp show-for-small-only\r\ndata-action|share/whatsapp/share"
    weight: '6'
    drupalSettings: ''
    library: ''
    text: ''
    img: ''
  email:
    enable: 0
    api_url: 'mailto:?subject=[current-page:title]&body=Check out this site [current-page:url]'
    api_event: href
    text: Email
    default_img: 1
    weight: '7'
    attributes: class|email
    drupalSettings: ''
    library: ''
    img: ''
    enable_forward: 0
    show_forward: '1'
  print:
    enable: 0
    api_url: window.print()
    api_event: onclick
    text: Print
    default_img: 1
    attributes: class|print
    weight: '8'
    drupalSettings: ''
    library: ''
    img: ''
langcode: fi
_core:
  default_config_hash: dfTa2HkSKvNWB_DYT7sVaiv7lztYl_vQaZyE9901WpE
