_core:
  default_config_hash: pM_g394SF1EVvpnCeq3-E1k6fGRelDP2ONHmdgJZcVE
langcode: fi
first_day: 1
country:
  default: FI
timezone:
  default: Europe/Helsinki
  user:
    configurable: false
    default: 0
    warn: false
