_core:
  default_config_hash: lgxMPy6JPv8qi2x7Dzesv2y5HXdubS5WsaL46KQoG1Y
api_urls:
  local: 'http://tampere.l/api/tre-content-listing'
  dev: 'https://web-dev.tampere.fi/api/tre-content-listing'
  staging: 'https://staging.tampere.fi/api/tre-content-listing'
  production: 'https://www.tampere.fi/api/tre-content-listing'
