_core:
  default_config_hash: wLhhL58IKPWkAbhxcI6gpCna7d431Q7kM0y-Om92BUQ
langcode: fi
warmers:
  jsonapi:
    id: jsonapi
    frequency: 300
    batchSize: 50
    resource_types:
      file--file: file--file
      media--dream_broker_video: media--dream_broker_video
      media--file: media--file
      media--image: media--image
      media--image_in_other_language: media--image_in_other_language
      media--remote_video: media--remote_video
      taxonomy_term--cross_site_publications: taxonomy_term--cross_site_publications
      taxonomy_term--personnel_companies: taxonomy_term--personnel_companies
      taxonomy_term--personnel_cost_centers: taxonomy_term--personnel_cost_centers
      taxonomy_term--personnel_organization_units: taxonomy_term--personnel_organization_units
      taxonomy_term--personnel_titles: taxonomy_term--personnel_titles
      block--block: '0'
      block_content_type--block_content_type: '0'
      comment_type--comment_type: '0'
      comment--blog_article_comment: '0'
      config_pages_type--config_pages_type: '0'
      config_pages--404_page_content: '0'
      config_pages--footer_information: '0'
      config_split--config_split: '0'
      content_moderation_state--content_moderation_state: '0'
      content_moderation_notification--content_moderation_notification: '0'
      crop--focal_point: '0'
      crop_type--crop_type: '0'
      editor--editor: '0'
      embederator--mediaserver_live: '0'
      embederator--mediaserver_video: '0'
      embederator--quickchannel_embed: '0'
      embederator_type--embederator_type: '0'
      entity_browser--entity_browser: '0'
      entity_log--entity_log: '0'
      environment_indicator--environment_indicator: '0'
      facets_facet--facets_facet: '0'
      facets_facet_source--facets_facet_source: '0'
      feeds_feed_type--feeds_feed_type: '0'
      feeds_feed--rss_feed: '0'
      feeds_subscription--feeds_subscription: '0'
      field_storage_config--field_storage_config: '0'
      field_config--field_config: '0'
      filter_format--filter_format: '0'
      group_content--group_content_type_07c6e9965f686: '0'
      group_content--group_content_type_0eff653d61300: '0'
      group_content--group_content_type_1bcd5b388ed86: '0'
      group_content--group_content_type_23d9f67219a89: '0'
      group_content--group_content_type_399819f395a9e: '0'
      group_content--group_content_type_3e00eae0ddb57: '0'
      group_content--group_content_type_3f47bfd30dcca: '0'
      group_content--group_content_type_459453987b921: '0'
      group_content--group_content_type_54e72f3acfa68: '0'
      group_content--group_content_type_636b622e9c5af: '0'
      group_content--group_content_type_791854d8dd98b: '0'
      group_content--group_content_type_7ca5a062ed2e5: '0'
      group_content--group_content_type_7d61b8d3b8736: '0'
      group_content--group_content_type_834a1a5784d1e: '0'
      group_content--group_content_type_8655c3d480a07: '0'
      group_content--group_content_type_94e899c8fb925: '0'
      group_content--group_content_type_9912c710aa585: '0'
      group_content--group_content_type_9e556b10a3693: '0'
      group_content--group_content_type_a26224e317972: '0'
      group_content--group_content_type_a29f3e69663e2: '0'
      group_content--group_content_type_b08008e9b7e4c: '0'
      group_content--group_content_type_be580e4460fc2: '0'
      group_content--group_content_type_c773cc495730b: '0'
      group_content--group_content_type_cd1e5bdc28a6f: '0'
      group_content--group_content_type_ce8aebe86d4d6: '0'
      group_content--group_content_type_d23d2b4b19ca1: '0'
      group_content--group_content_type_d579c14c7955a: '0'
      group_content--group_content_type_df352bd5fd507: '0'
      group_content--group_content_type_e2d67bdaab139: '0'
      group_content--group_content_type_e3adb31f025fd: '0'
      group_content--group_content_type_e82b99b0e3cc6: '0'
      group_content--group_content_type_ea92f456aacd5: '0'
      group_content--group_content_type_fe308d5f59604: '0'
      group_content--life_situation-group_membership: '0'
      group_content--life_situation-group_node-place: '0'
      group_content--minisite-group_membership: '0'
      group_content--minisite-group_node-front_page: '0'
      group_content--minisite-group_node-news_item: '0'
      group_content--minisite-group_node-organization: '0'
      group_content--minisite-group_node-place: '0'
      group_content--minisite-group_node-portfolio: '0'
      group_content--minisite-group_node-project: '0'
      group_content--subsite-group_membership: '0'
      group_content--subsite-group_node-organization: '0'
      group_content--subsite-group_node-place: '0'
      group_content--subsite-group_node-portfolio: '0'
      group_content--subsite-group_node-project: '0'
      group_content--theme-group_membership: '0'
      group_content--theme-group_node-collection_page: '0'
      group_content--theme-group_node-moderated_page: '0'
      group_content--theme-group_node-organization: '0'
      group_content--theme-group_node-place: '0'
      group_content--theme-group_node-portfolio: '0'
      group_content--theme-group_node-project: '0'
      group_content--topic-group_membership: '0'
      group_content--topic-group_node-collection_page: '0'
      group_content--topic-group_node-moderated_page: '0'
      group_content--topic-group_node-organization: '0'
      group_content--topic-group_node-place: '0'
      group_content--topic-group_node-portfolio: '0'
      group_content--topic-group_node-project: '0'
      group_content_type--group_content_type: '0'
      group_role--group_role: '0'
      group_type--group_type: '0'
      group--life_situation: '0'
      group--minisite: '0'
      group--subsite: '0'
      group--theme: '0'
      group--topic: '0'
      group_content_menu--minisite_main_menu_en: '0'
      group_content_menu--minisite_main_menu_fi: '0'
      group_content_menu--subsite_main_menu_en: '0'
      group_content_menu--subsite_main_menu_fi: '0'
      group_content_menu_type--group_content_menu_type: '0'
      image_style--image_style: '0'
      jsonapi_resource_config--jsonapi_resource_config: '0'
      language_content_settings--language_content_settings: '0'
      configurable_language--configurable_language: '0'
      linkit_profile--linkit_profile: '0'
      media_type--media_type: '0'
      media_bulk_config--media_bulk_config: '0'
      message--news_item_to_media: '0'
      message_template--message_template: '0'
      metatag_defaults--metatag_defaults: '0'
      migration--migration: '0'
      migration_group--migration_group: '0'
      node_type--node_type: '0'
      node--basic_content_page: '0'
      node--blog_article: '0'
      node--city_planning_and_constructions: '0'
      node--collection_page: '0'
      node--content_in_other_language: '0'
      node--emergency_notice: '0'
      node--front_page: '0'
      node--involvement_opportunity: '0'
      node--map_point: '0'
      node--moderated_page: '0'
      node--news_item: '0'
      node--notice: '0'
      node--organization: '0'
      node--person: '0'
      node--place: '0'
      node--place_of_business: '0'
      node--portfolio: '0'
      node--project: '0'
      node--ptv_service: '0'
      node--rich_article: '0'
      node--rss_item: '0'
      node--service_channel: '0'
      node--small_news_item: '0'
      node--zoning_information: '0'
      path_alias--path_alias: '0'
      role_change_log--role_change_log: '0'
      behavior_settings--behavior_settings: '0'
      redirect--redirect: '0'
      responsive_image_style--responsive_image_style: '0'
      role_watchdog--role_watchdog: '0'
      scheduled_transition--scheduled_transition: '0'
      search_api_server--search_api_server: '0'
      search_api_index--search_api_index: '0'
      search_api_task--search_api_task: '0'
      search_api_autocomplete_search--search_api_autocomplete_search: '0'
      solr_field_type--solr_field_type: '0'
      solr_request_dispatcher--solr_request_dispatcher: '0'
      solr_request_handler--solr_request_handler: '0'
      solr_cache--solr_cache: '0'
      simple_sitemap_type--simple_sitemap_type: '0'
      simple_sitemap--simple_sitemap: '0'
      menu--menu: '0'
      action--action: '0'
      taxonomy_vocabulary--taxonomy_vocabulary: '0'
      taxonomy_term--accessibility_and_service_infos: '0'
      taxonomy_term--blogs: '0'
      taxonomy_term--geographical_areas: '0'
      taxonomy_term--keywords: '0'
      taxonomy_term--life_situations: '0'
      taxonomy_term--mailing_lists: '0'
      taxonomy_term--media_folders: '0'
      taxonomy_term--minisites: '0'
      taxonomy_term--notice_types: '0'
      taxonomy_term--other_identifiers: '0'
      taxonomy_term--plan_numbers: '0'
      taxonomy_term--record_numbers: '0'
      taxonomy_term--service_classes: '0'
      taxonomy_term--topics: '0'
      taxonomy_term--zoning_information_types: '0'
      user--user: '0'
      user_role--user_role: '0'
      varnishpurgersettings--varnishpurgersettings: '0'
      webform_options--webform_options: '0'
      webform--webform: '0'
      webform_submission--kaavan_123_palautekysely: '0'
      webform_submission--kaavapalaute: '0'
      webform_submission--palaute: '0'
      workflow--workflow: '0'
      menu_link_content--account: '0'
      menu_link_content--admin: '0'
      menu_link_content--footer: '0'
      menu_link_content--footer-main-menu-en: '0'
      menu_link_content--footer-main-menu-fi: '0'
      menu_link_content--header-quick-links-en: '0'
      menu_link_content--header-quick-links-fi: '0'
      menu_link_content--life-situation-menu-en: '0'
      menu_link_content--life-situation-menu-fi: '0'
      menu_link_content--main: '0'
      menu_link_content--main-menu-en: '0'
      menu_link_content--main-menu-fi: '0'
      menu_link_content--secondary-menu-en: '0'
      menu_link_content--secondary-menu-fi: '0'
      menu_link_content--tools: '0'
      pathauto_pattern--pathauto_pattern: '0'
      view--view: '0'
      paragraphs_type--paragraphs_type: '0'
      paragraph--accordions: '0'
      paragraph--accordion_item: '0'
      paragraph--accordion_text_content: '0'
      paragraph--anchor_link: '0'
      paragraph--anchor_list: '0'
      paragraph--attachment: '0'
      paragraph--automatic_anchor_list: '0'
      paragraph--back_to_top_link: '0'
      paragraph--balanced_content_liftup: '0'
      paragraph--city_construction_project_card: '0'
      paragraph--city_construction_project_cards: '0'
      paragraph--colorful_content_liftup: '0'
      paragraph--contact_information_liftups: '0'
      paragraph--contact_information_list: '0'
      paragraph--content_liftup: '0'
      paragraph--course_listing: '0'
      paragraph--course_listing_sports: '0'
      paragraph--current_liftup: '0'
      paragraph--current_listing: '0'
      paragraph--downloadable_material: '0'
      paragraph--embedded_content_and_map_tabs: '0'
      paragraph--embederator_embed: '0'
      paragraph--event_and_hobby_listing: '0'
      paragraph--external_link: '0'
      paragraph--external_link_with_link_text: '0'
      paragraph--feedback_section: '0'
      paragraph--generic_listing: '0'
      paragraph--grouped_content_liftup: '0'
      paragraph--highlighted_content_liftup_w_img: '0'
      paragraph--highlighted_links_with_feedback: '0'
      paragraph--highlighted_link_list: '0'
      paragraph--icon_and_text_link: '0'
      paragraph--image: '0'
      paragraph--image_gallery: '0'
      paragraph--image_gallery_item: '0'
      paragraph--infograph: '0'
      paragraph--infographs: '0'
      paragraph--internal_link: '0'
      paragraph--internal_link_with_link_text: '0'
      paragraph--involvement_opportunity_card: '0'
      paragraph--involvement_opportunity_cards: '0'
      paragraph--link_list: '0'
      paragraph--list_of_attachments: '0'
      paragraph--login_link: '0'
      paragraph--login_link_with_text: '0'
      paragraph--mailing_list_information: '0'
      paragraph--map_embed: '0'
      paragraph--material_download_list: '0'
      paragraph--metadata_attachment_list: '0'
      paragraph--mosaic_liftup: '0'
      paragraph--notice: '0'
      paragraph--persons_contact_information_list: '0'
      paragraph--person_liftup: '0'
      paragraph--person_liftups: '0'
      paragraph--picture_mosaic: '0'
      paragraph--place_liftup: '0'
      paragraph--place_of_business_liftup: '0'
      paragraph--portfolio_content_listing: '0'
      paragraph--positioned_image: '0'
      paragraph--process_accordions: '0'
      paragraph--process_accordion_item: '0'
      paragraph--project_and_organization_cards: '0'
      paragraph--project_or_organization_card: '0'
      paragraph--ptv_service_liftup: '0'
      paragraph--rss_feed: '0'
      paragraph--separator: '0'
      paragraph--service_highlight: '0'
      paragraph--single_colorful_content_liftup: '0'
      paragraph--social_media_feed_embed: '0'
      paragraph--social_media_link: '0'
      paragraph--table: '0'
      paragraph--table_with_row_and_col_headers: '0'
      paragraph--table_with_row_headers: '0'
      paragraph--text: '0'
      paragraph--text_and_images: '0'
      paragraph--text_with_bgcolor: '0'
      paragraph--two_column_liftup: '0'
      paragraph--video_embed: '0'
      paragraph--webform: '0'
      paragraph--zoning_project_card: '0'
      paragraph--zoning_project_cards: '0'
      entity_view_mode--entity_view_mode: '0'
      entity_view_display--entity_view_display: '0'
      entity_form_mode--entity_form_mode: '0'
      entity_form_display--entity_form_display: '0'
      date_format--date_format: '0'
      base_field_override--base_field_override: '0'
  cdn:
    id: cdn
    frequency: 900
    batchSize: 20
    urls:
      - 'https://www.tampere.fi/api/node/news_item/?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&page[limit]=50&page[offset]=0'
      - 'https://www.tampere.fi/api/node/news_item?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&page[limit]=50&page[offset]=0'
      - 'https://www.tampere.fi/api/node/news_item?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&page[offset]=100&page[limit]=50&include=field_paragraphs%2Cfield_main_image.field_media_image%2Cfield_cross_site_publications%2Cfield_contact_info.field_person_liftup%2Cfield_minisites%2Cfield_life_situations%2Cfield_keywords%2Cfield_topics%2Cfield_geographical_areas'
      - 'https://www.tampere.fi/api/node/news_item?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&page[offset]=150&page[limit]=50&include=field_paragraphs%2Cfield_main_image.field_media_image%2Cfield_cross_site_publications%2Cfield_contact_info.field_person_liftup%2Cfield_minisites%2Cfield_life_situations%2Cfield_keywords%2Cfield_topics%2Cfield_geographical_areas'
      - 'https://www.tampere.fi/api/node/news_item?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&page[offset]=50&page[limit]=50&include=field_paragraphs%2Cfield_main_image.field_media_image%2Cfield_cross_site_publications%2Cfield_contact_info.field_person_liftup%2Cfield_minisites%2Cfield_life_situations%2Cfield_keywords%2Cfield_topics%2Cfield_geographical_areas'
      - 'https://www.tampere.fi/api/node/news_item?sort=-created&filter[langcode]=en'
      - 'https://www.tampere.fi/api/node/news_item?sort=-created&filter[langcode]=fi'
      - 'https://www.tampere.fi/en/api/node/news_item/?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&filter[lang][condition][path]=langcode&filter[lang][condition][value]=en&page[limit]=50&page[offset]=0'
      - 'https://www.tampere.fi/en/api/node/news_item?filter[published][condition][path]=status&filter[published][condition][value]=1&filter[publications][condition][path]=field_cross_site_publications&filter[publications][condition][operator]=IS NOT NULL&filter[lang][condition][path]=langcode&filter[lang][condition][value]=en&page[limit]=50&page[offset]=0'
    headers: {  }
    verify: false
    maxConcurrentRequests: 1
  sitemap:
    id: sitemap
    frequency: 900
    batchSize: 10
    minPriority: 0.0
    sitemaps: {  }
    headers: {  }
    verify: true
    maxConcurrentRequests: 1
