<?php

/**
 * @file
 * Contains tre_course_listing.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * @throws Exception
 */
function tre_course_listing_preprocess_paragraph__course_listing(&$variables) {
  return _tre_course_listing_preprocess_paragraph($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @throws Exception
 */
function tre_course_listing_preprocess_paragraph__course_listing_sports(&$variables) {
  return _tre_course_listing_preprocess_paragraph($variables);
}

/**
 * Helper function for processing course listing paragraphs.
 *
 * @param array $variables
 *   The parameter variables for the original preprocess hook.
 *
 * @return array
 *   The preprocessed variables as an array.
 */
function _tre_course_listing_preprocess_paragraph(array &$variables): array {
  $paragraph = $variables['paragraph'];

  $paragraph_id = $paragraph->id();
  $element_id = "course-listing-app-{$paragraph_id}";

  $variables['content']['#markup'] = "<div id='{$element_id}'></div>";

  $variables['content']['#attached']['library'] = [
    'tre_course_listing/course-listing-app',
  ];

  $paragraph_type = $paragraph->bundle();
  $course_data = \Drupal::service('tre_course_listing.courses')->getCourses($paragraph_id, $paragraph_type);

  /** @var \Drupal\Core\Entity\EntityRepositoryInterface $entity_repository */
  $entity_repository = \Drupal::service('entity.repository');

  /** @var \Drupal\paragraphs\ParagraphInterface $translated_paragraph */
  $translated_paragraph = $entity_repository->getTranslationFromContext($paragraph);

  // Sort courses by their starting date in descending order by default.
  $sort_value = 'date_desc';
  $translated_paragraph_has_sort_field = $translated_paragraph->hasField('field_course_sort_order');
  if ($translated_paragraph_has_sort_field && !$translated_paragraph->get('field_course_sort_order')->isEmpty()) {
    $sort_value = $translated_paragraph->get('field_course_sort_order')->getString();
  }

  $variables['content']['#attached']['drupalSettings']['tampere']['courseListings'][$paragraph_id] = [
    'title' => $translated_paragraph->get('field_title')->getString(),
    'description' => $translated_paragraph->get('field_summary')->getString(),
    'element_id' => $element_id,
    'courseData' => $course_data,
    'sort' => $sort_value,
    'bundle' => $paragraph_type,
  ];

  $variables['#cache']['tags'][] = 'timesup:minutely';

  return $variables;
}
